# Generated by Django 4.2.27 on 2026-03-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_image_purchase'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_purchase'),
        ),
    ]
