# Generated by Django 4.2.27 on 2026-03-04 15:30

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_purchase_unique_user_course_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(validators=[courses.models.validate_start_date]),
        ),
    ]
